### PR TITLE
chore: YoStarJP&KR 塵影に交わる残響 復刻

### PR DESCRIPTION
**Pull request by Manicsteiner**
请在至少5小时后合并此分支
~~超前预载~~

### CODE REVIEW

**Comment by ABA2396** [comment]
为什么要5小时后）

**Comment by Manicsteiner** [comment]
> 为什么要5小时后）

当前活动还没结束，我偷懒预载了

**Comment by Constrat** [comment]
Preloading could brake something also. the event starts on the 5th

**Comment by Constrat** [comment]
@Manicsteiner Now should be a good time, yes? The current event should have ended right?

**Comment by Constrat** [comment]
> @Constrat YoStarKR event has already ended

Then it should have also ended for ArknightsJP

**Pull request merged**
